export const LOAD_RESTAURANTS_MENU_START = 'LOAD_RESTAURANTS_MENU_START';
export const LOAD_RESTAURANTS_MENU_SUCCESS = 'LOAD_RESTAURANTS_MENU_SUCCESS';
export const LOAD_RESTAURANTS_MENU_FAIL = 'LOAD_RESTAURANTS_MENU_FAIL';
export const LOAD_RESTAURANTS_MENU_ADD = 'LOAD_RESTAURANTS_MENU_ADD';
export const LOAD_RESTAURANTS_MENU_CART = 'LOAD_RESTAURANTS_MENU_CART';
export const LOAD_RESTAURANTS_MENU_REMOVE = 'LOAD_RESTAURANTS_MENU_REMOVE';
export const LOAD_RESTAURANTS_MENU_REMOVE_ALL = 'LOAD_RESTAURANTS_MENU_REMOVE_ALL';
export const LOAD_RESTAURANTS_MENU_REMOVE_ELEMENT = 'LOAD_RESTAURANTS_MENU_REMOVE_ELEMENT';
