export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPDATE_MEAL_START = 'UPDATE_MEAL_START';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAIL = 'UPDATE_MEAL_FAIL';

export const ADD_MEAL_START = 'ADD_MEAL_START';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAIL = 'ADD_MEAL_FAIL';

export const GET_DISH_START = 'GET_DISH_START';
export const GET_DISH_SUCCESS = 'GET_DISH_SUCCESS';
export const GET_DISH_CAT_SUCCESS = 'GET_DISH_CAT_SUCCESS';
export const GET_DISH_FAIL = 'GET_DISH_FAIL';

