export const SET_DELIVERY_START_ANYTHING = ' SET_DELIVERY_START_ANYTHING';
export const SET_DELIVERY_FAILED = ' SET_DELIVERY_FAILED';
export const SET_DELIVERY_TIME = ' SET_DELIVERY_TIME';
export const SET_DELIVERY_DATE = ' SET_DELIVERY_DATE';
export const SET_DELIVERY_POSTCODE = ' SET_DELIVERY_POSTCODE';
export const SET_DELIVERY_AMOUNT = ' SET_DELIVERY_AMOUNT';
export const SET_DELIVERY_FOODS = ' SET_DELIVERY_FOODS';

export const SET_ORDER_FOODS_START = 'SET_ORDER_FOODS_START';
export const SET_ORDER_FOODS_SUCCESS = 'SET_ORDER_FOODS_SUCCESS';
export const SET_ORDER_FOODS_FAIL = 'SET_ORDER_FOODS_FAIL';
