export  const  REGISTER_RESTAURANTS_START = "REGISTER_RESTAURANTS_START";
export  const  REGISTER_RESTAURANTS_FAIL =  "REGISTER_RESTAURANTS_FAIL";
export  const  REGISTER_RESTAURANTS_SUCCESS = "REGISTER_RESTAURANTS_SUCCESS";
