export  const  REGISTER_CONTACT_START = "REGISTER_CONTACT_START";
export  const  REGISTER_CONTACT_FAIL =  "REGISTER_CONTACT_FAIL";
export  const  REGISTER_CONTACT_SUCCESS = "REGISTER_CONTACT_SUCCESS";
