export const LOAD_RESTAURANTS_START = 'LOAD_RESTAURANTS_START';
export const LOAD_RESTAURANTS_SUCCESS = 'LOAD_RESTAURANTS_SUCCESS';
export const LOAD_RESTAURANTS_FAIL = 'LOAD_RESTAURANTS_FAIL';


export const LOAD_CATEGORIES_START = 'LOAD_CATEGORIES_START';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL';
