export  const  REGISTER_DELIVERY_START = "REGISTER_DELIVERY_START";
export  const  REGISTER_DELIVERY_FAIL =  "REGISTER_DELIVERY_FAIL";
export  const  REGISTER_DELIVERY_SUCCESS = "REGISTER_DELVERY_SUCCESS";
