export const LOAD_VALIDATION_START = 'LOAD_VALIDATION_START';
export const LOAD_VALIDATION_SUCCESS = 'LOAD_VALIDATION_SUCCESS';
export const LOAD_VALIDATION_FAIL = 'LOAD_VALIDATION_FAIL';

export const LOAD_ORDERS_START = 'LOAD_ORDERS_START';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ACCEPT_ACCOUNT = 'ACCEPT_ACCOUNT';
